import { Category, Experience } from '../types';

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-attractions', name: 'Attractions', slug: 'attractions', icon: 'Compass', sortOrder: 1 },
  { id: 'cat-museums', name: 'Museums', slug: 'museums', icon: 'Landmark', sortOrder: 2 },
  { id: 'cat-food', name: 'Food', slug: 'food', icon: 'UtensilsCrossed', sortOrder: 3 },
  { id: 'cat-parks', name: 'Parks', slug: 'parks', icon: 'Trees', sortOrder: 4 },
  { id: 'cat-nightlife', name: 'Nightlife', slug: 'nightlife', icon: 'Moon', sortOrder: 5 },
  { id: 'cat-adventure', name: 'Adventure', slug: 'adventure', icon: 'Mountain', sortOrder: 6 },
  { id: 'cat-events', name: 'Events', slug: 'events', icon: 'Calendar', sortOrder: 7 },
];

export const SEED_EXPERIENCES: Experience[] = [
  // ==========================================
  // BENGALURU EXPERIENCES
  // ==========================================
  {
    id: 'blr-palace',
    title: 'Bangalore Palace',
    description: 'Tudor-style royal estate with wooden carvings, grand chandeliers, and expansive manicured gardens built by Chamaraja Wodeyar in 1878.',
    category: 'Attractions',
    city: 'Bengaluru',
    latitude: 12.9988,
    longitude: 77.5921,
    address: 'Vasanth Nagar, Bengaluru, Karnataka 560052',
    rating: 4.6,
    reviewCount: 4820,
    priceTier: '$$',
    priceAmount: 250,
    durationMinutes: 120,
    openingHours: '10:00 - 17:30',
    imageUrl: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    tags: ['Historic', 'Royal Heritage', 'Architecture', 'Audio Tour'],
    isFeatured: true,
  },
  {
    id: 'blr-visvesvaraya',
    title: 'Visvesvaraya Industrial & Technological Museum',
    description: 'Interactive science wonderland with four floors of hands-on exhibits, aerospace engine models, biotechnology displays, and 3D dinosaur shows.',
    category: 'Museums',
    city: 'Bengaluru',
    latitude: 12.9752,
    longitude: 77.5963,
    address: 'Kasturba Road, Sampangi Rama Nagar, Bengaluru 560001',
    rating: 4.7,
    reviewCount: 3640,
    priceTier: '$',
    priceAmount: 85,
    durationMinutes: 120,
    openingHours: '09:30 - 18:00',
    imageUrl: 'https://images.unsplash.com/photo-1569437061241-a848be43cc82?auto=format&fit=crop&w=1200&q=80',
    tags: ['Science', 'Family Friendly', 'Interactive', 'Tech'],
    isFeatured: true,
  },
  {
    id: 'blr-cubbon-park',
    title: 'Cubbon Park',
    description: 'A 300-acre lush green haven nestled in the heart of Bengaluru, shaded by bamboo groves, colonial memorials, and serene walking tracks.',
    category: 'Parks',
    city: 'Bengaluru',
    latitude: 12.9763,
    longitude: 77.5929,
    address: 'Kasturba Road, Bengaluru, Karnataka 560001',
    rating: 4.8,
    reviewCount: 9150,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '06:00 - 19:00',
    imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Nature', 'Walking', 'Peaceful', 'Picnic Spot'],
    isFeatured: true,
  },
  {
    id: 'blr-toit',
    title: 'Toit Brewpub Indiranagar',
    description: 'Iconic microbrewery celebrated for craft ales, Tint-in-Wit Belgian beer, wood-fired pizza, and an unbeatable weekend social vibe.',
    category: 'Nightlife',
    city: 'Bengaluru',
    latitude: 12.9792,
    longitude: 77.6408,
    address: '100ft Road, Indiranagar, Bengaluru 560038',
    rating: 4.8,
    reviewCount: 11200,
    priceTier: '$$$',
    priceAmount: 1200,
    durationMinutes: 150,
    openingHours: '12:00 - 00:30',
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
    tags: ['Craft Beer', 'Dining', 'Vibrant', 'Social Hub'],
    isFeatured: false,
  },
  {
    id: 'blr-vidyarthi-bhavan',
    title: 'Vidyarthi Bhavan Masala Dosa',
    description: 'Legendary Gandhi Bazaar heritage restaurant serving crispy ghee-laden masala dosas and frothy filter coffee since 1943.',
    category: 'Food',
    city: 'Bengaluru',
    latitude: 12.9431,
    longitude: 77.5714,
    address: 'Gandhi Bazaar Main Rd, Basavanagudi, Bengaluru 560004',
    rating: 4.7,
    reviewCount: 8400,
    priceTier: '$',
    priceAmount: 120,
    durationMinutes: 60,
    openingHours: '06:30 - 11:30, 14:00 - 20:00',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80',
    tags: ['South Indian', 'Breakfast', 'Heritage', 'Filter Coffee'],
    isFeatured: true,
  },
  {
    id: 'blr-lalbagh',
    title: 'Lalbagh Botanical Garden & Glass House',
    description: 'Historic 240-acre botanical reserve commissioned by Hyder Ali, featuring century-old trees, a serene lotus lake, and the famed Victorian glass pavilion.',
    category: 'Parks',
    city: 'Bengaluru',
    latitude: 12.9507,
    longitude: 77.5848,
    address: 'Mavalli, Bengaluru, Karnataka 560004',
    rating: 4.7,
    reviewCount: 7800,
    priceTier: '$',
    priceAmount: 30,
    durationMinutes: 120,
    openingHours: '06:00 - 19:00',
    imageUrl: 'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?auto=format&fit=crop&w=1200&q=80',
    tags: ['Botany', 'Photography', 'Historic Trees', 'Morning Walk'],
    isFeatured: false,
  },
  {
    id: 'blr-bannerghatta',
    title: 'Bannerghatta Tiger & Lion Safari',
    description: 'Thrilling open wildlife safari across rugged forest enclosures to observe Bengal tigers, lions, and Asian elephants, with an adjoining butterfly park.',
    category: 'Adventure',
    city: 'Bengaluru',
    latitude: 12.8009,
    longitude: 77.5777,
    address: 'Bannerghatta Main Rd, Bannerghatta, Bengaluru 560083',
    rating: 4.5,
    reviewCount: 5200,
    priceTier: '$$',
    priceAmount: 350,
    durationMinutes: 180,
    openingHours: '09:30 - 17:00 (Tue Closed)',
    imageUrl: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Wildlife', 'Safari', 'Big Cats', 'Adventure'],
    isFeatured: true,
  },
  {
    id: 'blr-tipu-palace',
    title: "Tipu Sultan's Summer Palace",
    description: 'Graceful Indo-Islamic teakwood palace completed in 1791, adorned with ornate arches, stone pillars, and historical battle memorabilia.',
    category: 'Attractions',
    city: 'Bengaluru',
    latitude: 12.9593,
    longitude: 77.5737,
    address: 'Albert Victor Road, Chamrajpet, Bengaluru 560018',
    rating: 4.4,
    reviewCount: 3100,
    priceTier: '$',
    priceAmount: 25,
    durationMinutes: 60,
    openingHours: '08:30 - 17:30',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    tags: ['Historic', 'Teakwood Architecture', 'Museum'],
    isFeatured: false,
  },
  {
    id: 'blr-fandom',
    title: "Live Concert & Indie Night at Fandom",
    description: 'Premier live performance amphitheater hosting top indie bands, electronic producers, and stand-up comics with state-of-the-art acoustics.',
    category: 'Events',
    city: 'Bengaluru',
    latitude: 12.9237,
    longitude: 77.6214,
    address: '1st Main Rd, 4th Block, Koramangala, Bengaluru 560034',
    rating: 4.6,
    reviewCount: 1980,
    priceTier: '$$$',
    priceAmount: 800,
    durationMinutes: 180,
    openingHours: '19:30 - 01:00',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
    tags: ['Live Music', 'Indie Rock', 'Concert', 'Cocktails'],
    isFeatured: false,
  },
  {
    id: 'blr-ngma',
    title: 'National Gallery of Modern Art (NGMA)',
    description: 'Stunning colonial mansion set around a reflection pool, displaying sculptures and masterpieces by Raja Ravi Varma and Jamini Roy.',
    category: 'Museums',
    city: 'Bengaluru',
    latitude: 12.9898,
    longitude: 77.5878,
    address: '49, Palace Rd, Manikyavelu Mansion, Vasanth Nagar, Bengaluru 560052',
    rating: 4.7,
    reviewCount: 2200,
    priceTier: '$',
    priceAmount: 50,
    durationMinutes: 90,
    openingHours: '10:00 - 18:00 (Mon Closed)',
    imageUrl: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=1200&q=80',
    tags: ['Modern Art', 'Sculpture', 'Peaceful Cafe', 'Cultural'],
    isFeatured: false,
  },
  {
    id: 'blr-church-street',
    title: 'Church Street Evening Promenade & Bookstore Crawl',
    description: 'Cobblestone pedestrianized boulevard famous for indie secondhand bookshops like Blossom Book House, animated street buskers, and artisan coffee roasters.',
    category: 'Attractions',
    city: 'Bengaluru',
    latitude: 12.9749,
    longitude: 77.6048,
    address: 'Church Street, Shanthala Nagar, Bengaluru 560001',
    rating: 4.8,
    reviewCount: 9900,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '11:00 - 23:00',
    imageUrl: 'https://images.unsplash.com/photo-1507842229451-77b103b7a5a8?auto=format&fit=crop&w=1200&q=80',
    tags: ['Books', 'Cafes', 'Walkable', 'Vibrant'],
    isFeatured: false,
  },

  // ==========================================
  // MUMBAI EXPERIENCES
  // ==========================================
  {
    id: 'mum-gateway',
    title: 'Gateway of India',
    description: 'Grand Indo-Saracenic basalt arch built overlooking the Arabian Sea, standing as the quintessential monument of Mumbai since 1924.',
    category: 'Attractions',
    city: 'Mumbai',
    latitude: 18.9220,
    longitude: 72.8347,
    address: 'Apollo Bandar, Colaba, Mumbai, Maharashtra 400001',
    rating: 4.7,
    reviewCount: 16500,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 60,
    openingHours: 'Open 24 hours',
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Iconic Landmark', 'Arabian Sea', 'Photography', 'Heritage'],
    isFeatured: true,
  },
  {
    id: 'mum-marine-drive',
    title: 'Marine Drive "Queen\'s Necklace" Promenade',
    description: 'A breezy 3.6-kilometer seaside boulevard hugging Back Bay, famous for sunset watchers, Art Deco buildings, and night-lit curving streetlamps.',
    category: 'Parks',
    city: 'Mumbai',
    latitude: 18.9432,
    longitude: 72.8230,
    address: 'Netaji Subhash Chandra Bose Road, Mumbai 400020',
    rating: 4.9,
    reviewCount: 21000,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: 'Open 24 hours',
    imageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80',
    tags: ['Sunset', 'Sea Breeze', 'Art Deco', 'Iconic Walk'],
    isFeatured: true,
  },
  {
    id: 'mum-csmvs-museum',
    title: 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya (CSMVS)',
    description: 'Premier heritage museum housed under an immense Rajput-Mughal dome, housing 70,000 artifacts from the Indus Valley Civilization to Tibetan bronzes.',
    category: 'Museums',
    city: 'Mumbai',
    latitude: 18.9269,
    longitude: 72.8327,
    address: '159-161, Mahatma Gandhi Road, Kala Ghoda, Mumbai 400023',
    rating: 4.8,
    reviewCount: 6300,
    priceTier: '$',
    priceAmount: 150,
    durationMinutes: 150,
    openingHours: '10:15 - 18:00',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    tags: ['Ancient History', 'Fine Arts', 'Gardens', 'Heritage'],
    isFeatured: true,
  },
  {
    id: 'mum-elephanta-caves',
    title: 'Elephanta Caves Island Excursion',
    description: 'UNESCO World Heritage rock-cut temples dating to the 5th century, featuring the awe-inspiring 20-foot three-headed Sadashiva sculpture reached by ferry.',
    category: 'Adventure',
    city: 'Mumbai',
    latitude: 18.9633,
    longitude: 72.9315,
    address: 'Gharapuri Island, Mumbai Harbour, Maharashtra 400094',
    rating: 4.6,
    reviewCount: 5400,
    priceTier: '$$',
    priceAmount: 300,
    durationMinutes: 240,
    openingHours: '09:00 - 17:30 (Mon Closed)',
    imageUrl: 'https://images.unsplash.com/photo-1600100397608-f010e421d015?auto=format&fit=crop&w=1200&q=80',
    tags: ['Ferry Ride', 'UNESCO Site', 'Ancient Carvings', 'Island'],
    isFeatured: true,
  },
  {
    id: 'mum-leopold-cafe',
    title: 'Leopold Cafe & Bar',
    description: 'Historic Colaba eatery founded in 1871, immortalized in the novel Shantaram, known for chilled draft beer, chicken stroganoff, and bustling global crowd.',
    category: 'Nightlife',
    city: 'Mumbai',
    latitude: 18.9228,
    longitude: 72.8317,
    address: 'Colaba Causeway, Apollo Bandar, Colaba, Mumbai 400001',
    rating: 4.5,
    reviewCount: 9200,
    priceTier: '$$',
    priceAmount: 850,
    durationMinutes: 90,
    openingHours: '07:30 - 00:00',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Historic Pub', 'Shantaram', 'Classic Mumbai', 'Casual Dining'],
    isFeatured: false,
  },
  {
    id: 'mum-chowpatty-food',
    title: 'Street Food Crawl at Girgaon Chowpatty',
    description: 'Savor spicy pav bhaji slathered with Amul butter, tangy bhel puri, and saffron rabdi kulfi directly facing the twilight sea.',
    category: 'Food',
    city: 'Mumbai',
    latitude: 18.9548,
    longitude: 72.8142,
    address: 'Girgaon Chowpatty, Marine Drive, Mumbai 400007',
    rating: 4.7,
    reviewCount: 7100,
    priceTier: '$',
    priceAmount: 180,
    durationMinutes: 75,
    openingHours: '16:00 - 23:30',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80',
    tags: ['Street Food', 'Pav Bhaji', 'Chaat', 'Beachside'],
    isFeatured: true,
  },
  {
    id: 'mum-sanjay-gandhi-np',
    title: 'Sanjay Gandhi National Park & Kanheri Caves',
    description: 'A 100-square-kilometer tropical forest reserve within city limits, hiding 109 ancient Buddhist basalt caves carved into mountain cliffs.',
    category: 'Adventure',
    city: 'Mumbai',
    latitude: 19.2288,
    longitude: 72.9106,
    address: 'Western Express Hwy, Borivali East, Mumbai 400066',
    rating: 4.6,
    reviewCount: 4900,
    priceTier: '$',
    priceAmount: 100,
    durationMinutes: 210,
    openingHours: '07:30 - 18:30 (Mon Closed)',
    imageUrl: 'https://images.unsplash.com/photo-1608755728617-aefab37d2edd?auto=format&fit=crop&w=1200&q=80',
    tags: ['Hiking', 'Buddhist Caves', 'Forest', 'Cycling'],
    isFeatured: false,
  },
  {
    id: 'mum-bandra-bandstand',
    title: 'Bandra Bandstand & Castella de Aguada',
    description: 'Rocky seaside promontory topped with 1640 Portuguese fort ruins, panoramic sea-link vistas, and Bollywood celebrity manor views.',
    category: 'Attractions',
    city: 'Mumbai',
    latitude: 19.0416,
    longitude: 72.8197,
    address: 'BJ Road, Bandstand Promenade, Bandra West, Mumbai 400050',
    rating: 4.7,
    reviewCount: 8800,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '06:00 - 21:00',
    imageUrl: 'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=1200&q=80',
    tags: ['Sea Link View', 'Historic Fort', 'Sunset Walk', 'Bandra'],
    isFeatured: false,
  },
  {
    id: 'mum-ncpa-theatre',
    title: 'Symphony & Theatre Evening at NCPA',
    description: 'India’s premier cultural center showcasing performances by the Symphony Orchestra of India, classic Hindustani recitals, and modern plays.',
    category: 'Events',
    city: 'Mumbai',
    latitude: 18.9248,
    longitude: 72.8206,
    address: 'Nariman Point, Marine Drive, Mumbai 400021',
    rating: 4.8,
    reviewCount: 3100,
    priceTier: '$$$',
    priceAmount: 1200,
    durationMinutes: 150,
    openingHours: '18:00 - 22:30',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
    tags: ['Orchestra', 'Performing Arts', 'Live Theatre', 'Nariman Point'],
    isFeatured: false,
  },
  {
    id: 'mum-britannia',
    title: 'Britannia & Co. Parsi Berry Pulao',
    description: 'Time-warp 1923 colonial cafe in Ballard Estate legendary for fragrant Iranian berry pulao, caramel custard, and fresh lime soda.',
    category: 'Food',
    city: 'Mumbai',
    latitude: 18.9351,
    longitude: 72.8384,
    address: 'Wakefield House, 11 Sprott Rd, Ballard Estate, Mumbai 400001',
    rating: 4.6,
    reviewCount: 4200,
    priceTier: '$$',
    priceAmount: 450,
    durationMinutes: 60,
    openingHours: '12:00 - 16:00 (Sun Closed)',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80',
    tags: ['Parsi Cuisine', 'Berry Pulao', 'Ballard Estate', 'Heritage'],
    isFeatured: false,
  },

  // ==========================================
  // LONDON EXPERIENCES
  // ==========================================
  {
    id: 'lon-tower',
    title: 'Tower of London & Crown Jewels',
    description: 'Nearly 1,000 years of royal intrigue, medieval fortresses, White Tower armory, and the dazzling priceless Crown Jewels guarded by the Beefeaters.',
    category: 'Attractions',
    city: 'London',
    latitude: 51.5081,
    longitude: -0.0759,
    address: 'London EC3N 4AB, United Kingdom',
    rating: 4.8,
    reviewCount: 18200,
    priceTier: '$$$',
    priceAmount: 34,
    durationMinutes: 180,
    openingHours: '09:00 - 17:30',
    imageUrl: 'https://images.unsplash.com/photo-1520986606214-8b456906c813?auto=format&fit=crop&w=1200&q=80',
    tags: ['Royal History', 'Crown Jewels', 'Medieval Fortress', 'River Thames'],
    isFeatured: true,
  },
  {
    id: 'lon-british-museum',
    title: 'The British Museum & Great Court',
    description: 'World-renowned treasury of 8 million works exploring human history and culture, including the Rosetta Stone and Parthenon Sculptures.',
    category: 'Museums',
    city: 'London',
    latitude: 51.5194,
    longitude: -0.1270,
    address: 'Great Russell St, Bloomsbury, London WC1B 3DG',
    rating: 4.9,
    reviewCount: 24500,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 180,
    openingHours: '10:00 - 17:00 (Fri till 20:30)',
    imageUrl: 'https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?auto=format&fit=crop&w=1200&q=80',
    tags: ['Ancient Civilizations', 'Rosetta Stone', 'Glass Dome', 'Must Visit'],
    isFeatured: true,
  },
  {
    id: 'lon-sky-garden',
    title: 'Sky Garden 360 Lookout',
    description: 'London’s highest landscaped public gardens offering panoramic floor-to-ceiling glass views of London’s skyline, St Paul’s, and the River Thames.',
    category: 'Attractions',
    city: 'London',
    latitude: 51.5113,
    longitude: -0.0836,
    address: '1 Sky Garden Walk, London EC3M 8AF',
    rating: 4.8,
    reviewCount: 14200,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 75,
    openingHours: '10:00 - 18:00 (Requires free advance slot)',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
    tags: ['Skyline Views', 'Indoor Garden', 'Cocktails', 'Architecture'],
    isFeatured: true,
  },
  {
    id: 'lon-borough-market',
    title: 'Borough Market Artisanal Food Tour',
    description: 'Historic market under Victorian railway arches packed with artisan cheesemongers, sizzling chorizo rolls, freshly shucked oysters, and handmade pasta.',
    category: 'Food',
    city: 'London',
    latitude: 51.5055,
    longitude: -0.0906,
    address: '8 Southwark St, London SE1 1TL',
    rating: 4.8,
    reviewCount: 16900,
    priceTier: '$$',
    priceAmount: 22,
    durationMinutes: 90,
    openingHours: '10:00 - 17:00 (Sun 10:00 - 15:00)',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Gourmet Street Food', 'Cheese & Wine', 'Historic Market', 'Fresh Produce'],
    isFeatured: true,
  },
  {
    id: 'lon-hyde-park',
    title: 'Hyde Park & Serpentine Boating',
    description: 'Iconic 350-acre royal park with pedal boats on the Serpentine Lake, Diana Memorial Fountain, and wide tree-lined chestnut paths.',
    category: 'Parks',
    city: 'London',
    latitude: 51.5073,
    longitude: -0.1657,
    address: 'Hyde Park, London W2 2UH',
    rating: 4.7,
    reviewCount: 15100,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '05:00 - 00:00',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    tags: ['Boating', 'Royal Parks', 'Open Lawns', 'Relaxation'],
    isFeatured: false,
  },
  {
    id: 'lon-west-end',
    title: 'West End Musical at Lyceum Theatre',
    description: 'Immerse in world-class theatrical brilliance with dazzling costumes, live orchestral score, and breathtaking stage puppetry in Covent Garden.',
    category: 'Events',
    city: 'London',
    latitude: 51.5117,
    longitude: -0.1200,
    address: '21 Wellington St, London WC2E 7RQ',
    rating: 4.9,
    reviewCount: 8200,
    priceTier: '$$$',
    priceAmount: 65,
    durationMinutes: 150,
    openingHours: '19:30 showtime (Matinees on Wed/Sat)',
    imageUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=1200&q=80',
    tags: ['Musical', 'West End', 'Live Theatre', 'Covent Garden'],
    isFeatured: true,
  },
  {
    id: 'lon-tate-modern',
    title: 'Tate Modern & Turbine Hall',
    description: 'Housed in the colossal former Bankside Power Station on the South Bank, displaying groundbreaking international modern and contemporary art.',
    category: 'Museums',
    city: 'London',
    latitude: 51.5076,
    longitude: -0.0994,
    address: 'Bankside, London SE1 9TG',
    rating: 4.7,
    reviewCount: 13400,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 120,
    openingHours: '10:00 - 18:00',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80',
    tags: ['Modern Art', 'Turbine Hall', 'Picasso', 'South Bank'],
    isFeatured: false,
  },
  {
    id: 'lon-dishoom',
    title: 'Dishoom Bombay Comfort Dining',
    description: 'Atmospheric homage to old Irani cafes of Bombay with velvety House Black Daal, fragrant lamb biryani, and craft botanicals in Covent Garden.',
    category: 'Food',
    city: 'London',
    latitude: 51.5126,
    longitude: -0.1265,
    address: '12 Upper St Martin\'s Lane, London WC2H 9FB',
    rating: 4.8,
    reviewCount: 9800,
    priceTier: '$$',
    priceAmount: 28,
    durationMinutes: 90,
    openingHours: '08:00 - 23:00',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    tags: ['Bombay Cafe', 'Black Daal', 'Covent Garden', 'Atmospheric'],
    isFeatured: false,
  },
  {
    id: 'lon-greenwich',
    title: 'Greenwich Royal Observatory & Prime Meridian',
    description: 'Stand straddling the historic Prime Meridian line where East meets West (Longitude 0°), with views across the Thames to Canary Wharf.',
    category: 'Attractions',
    city: 'London',
    latitude: 51.4769,
    longitude: 0.0005,
    address: 'Blackheath Ave, London SE10 8XJ',
    rating: 4.7,
    reviewCount: 7600,
    priceTier: '$$',
    priceAmount: 18,
    durationMinutes: 120,
    openingHours: '10:00 - 17:00',
    imageUrl: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=1200&q=80',
    tags: ['Prime Meridian', 'Astronomy', 'Greenwich Park', 'Views'],
    isFeatured: false,
  },
  {
    id: 'lon-soho-jazz',
    title: 'Late Night Jazz at Ronnie Scott\'s',
    description: 'World-famous Soho jazz basement hosting legendary international performers, vintage martinis, and intimate cabaret table seating since 1959.',
    category: 'Nightlife',
    city: 'London',
    latitude: 51.5133,
    longitude: -0.1311,
    address: '47 Frith St, London W1D 4HT',
    rating: 4.8,
    reviewCount: 4500,
    priceTier: '$$$',
    priceAmount: 45,
    durationMinutes: 150,
    openingHours: '18:00 - 02:00',
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1200&q=80',
    tags: ['Jazz Club', 'Soho Nightlife', 'Live Music', 'Martinis'],
    isFeatured: false,
  },
  {
    id: 'lon-camden-market',
    title: 'Camden Lock & Stables Market',
    description: 'Vibrant maze of over 1,000 stalls packed with vintage clothes, alternative crafts, street food from 40 nations, and indie art along Regent\'s Canal.',
    category: 'Attractions',
    city: 'London',
    latitude: 51.5414,
    longitude: -0.1466,
    address: 'Camden Lock Place, London NW1 8AF',
    rating: 4.6,
    reviewCount: 15900,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 120,
    openingHours: '10:00 - 19:00',
    imageUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    tags: ['Street Market', 'Vintage', 'Regent Canal', 'Eclectic'],
    isFeatured: false,
  },

  // ==========================================
  // EXPANDED ROAMLY EXPERIENCES (50+ TOTAL)
  // ==========================================
  // Bengaluru
  {
    id: 'blr-ctr',
    title: 'CTR (Shri Sagar) Butter Masala Dosa',
    description: 'Historic 1920s cafe in Malleshwaram famous across India for golden-brown, crispy Benne Masala Dosa with coconut chutney and frothy filter coffee.',
    category: 'Food',
    city: 'Bengaluru',
    latitude: 13.0033,
    longitude: 77.5694,
    address: '7th Cross, Margosa Rd, Malleshwaram, Bengaluru 560003',
    rating: 4.8,
    reviewCount: 9500,
    priceTier: '$',
    priceAmount: 110,
    durationMinutes: 45,
    openingHours: '07:30 - 12:30, 16:00 - 21:00',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80',
    tags: ['Breakfast', 'Benne Dosa', 'Heritage', 'Iconic', 'Culture'],
    isFeatured: true,
  },
  {
    id: 'blr-ranga-shankara',
    title: 'Ranga Shankara Theatre & Courtyard Cafe',
    description: 'Vibrant non-profit theatre space staging contemporary plays 6 days a week, with an aromatic courtyard serving famous sabudana vadas and ginger chai.',
    category: 'Events',
    city: 'Bengaluru',
    latitude: 12.9116,
    longitude: 77.5878,
    address: '36/2, 8th Cross Rd, JP Nagar 2nd Phase, Bengaluru 560078',
    rating: 4.8,
    reviewCount: 4200,
    priceTier: '$$',
    priceAmount: 300,
    durationMinutes: 120,
    openingHours: '18:00 - 22:00 (Mon Closed)',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
    tags: ['Theatre', 'Live Play', 'Cultural Hub', 'Art', 'History'],
    isFeatured: false,
  },
  {
    id: 'blr-ime',
    title: 'Indian Music Experience Museum (IME)',
    description: 'India\'s first interactive music museum with nine experiential galleries, interactive instrument installations, and rare archival recordings.',
    category: 'Museums',
    city: 'Bengaluru',
    latitude: 12.8906,
    longitude: 77.5855,
    address: 'Brigade Millennium, JP Nagar 7th Phase, Bengaluru 560078',
    rating: 4.7,
    reviewCount: 2300,
    priceTier: '$$',
    priceAmount: 250,
    durationMinutes: 120,
    openingHours: '10:00 - 18:00 (Mon Closed)',
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1200&q=80',
    tags: ['Interactive Sound', 'Music History', 'Instruments', 'Art'],
    isFeatured: false,
  },
  {
    id: 'blr-bouldering',
    title: 'Bangalore Climbing Centre Bouldering',
    description: 'Premier urban indoor and outdoor rock climbing gym offering beginner bouldering sessions, technical problem walls, and supportive coaches.',
    category: 'Adventure',
    city: 'Bengaluru',
    latitude: 12.9815,
    longitude: 77.6350,
    address: 'Indiranagar 1st Stage, Bengaluru 560038',
    rating: 4.6,
    reviewCount: 1200,
    priceTier: '$$',
    priceAmount: 400,
    durationMinutes: 90,
    openingHours: '07:00 - 21:00',
    imageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
    tags: ['Rock Climbing', 'Bouldering', 'Adventure', 'Sports', 'Indoor'],
    isFeatured: false,
  },
  {
    id: 'blr-commercial-street',
    title: 'Commercial Street Artisan & Silk Bazaars',
    description: 'A bustling pedestrian shopper paradise famous for Kashmiri shawls, handcrafted brass, silver jewelry, and street stalls.',
    category: 'Attractions',
    city: 'Bengaluru',
    latitude: 12.9822,
    longitude: 77.6083,
    address: 'Commercial Street, Tasker Town, Bengaluru 560001',
    rating: 4.5,
    reviewCount: 14000,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 120,
    openingHours: '11:00 - 21:00',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Shopping', 'Street Market', 'Fabrics', 'Culture', 'Outdoor'],
    isFeatured: false,
  },
  {
    id: 'blr-sankey-tank',
    title: 'Sankey Tank Lakeside Sunset Walk',
    description: 'Serene 37-acre manmade lake built in 1882, featuring scenic paved walking promenades, landscaped island bird sanctuaries, and boat rides.',
    category: 'Parks',
    city: 'Bengaluru',
    latitude: 13.0076,
    longitude: 77.5746,
    address: 'Sadashiva Nagar, Bengaluru, Karnataka 560080',
    rating: 4.6,
    reviewCount: 5600,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 60,
    openingHours: '06:00 - 20:00',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    tags: ['Lakeside', 'Sunset Walk', 'Birds', 'Peaceful', 'Nature'],
    isFeatured: false,
  },
  {
    id: 'blr-corner-house',
    title: 'Corner House "Death by Chocolate"',
    description: 'Cult Bengaluru dessert institution celebrated for the legendary DBC: warm chocolate cake loaded with vanilla ice cream, hot fudge, and roasted peanuts.',
    category: 'Food',
    city: 'Bengaluru',
    latitude: 12.9733,
    longitude: 77.6085,
    address: 'Residency Rd, Shanthala Nagar, Bengaluru 560025',
    rating: 4.9,
    reviewCount: 12500,
    priceTier: '$',
    priceAmount: 180,
    durationMinutes: 40,
    openingHours: '11:00 - 23:30',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=80',
    tags: ['Dessert', 'DBC', 'Late Night', 'Food', 'Legendary'],
    isFeatured: false,
  },

  // Mumbai
  {
    id: 'mum-prithvi',
    title: 'Prithvi Theatre & Irish Coffee at Juhu',
    description: 'Iconic open community theatre established by Shashi Kapoor, with a welcoming open-air candlelit cafe known for Irish coffee and parathas.',
    category: 'Events',
    city: 'Mumbai',
    latitude: 19.1062,
    longitude: 72.8258,
    address: '20 Janki Kutir, Juhu Church Rd, Mumbai 400049',
    rating: 4.9,
    reviewCount: 8800,
    priceTier: '$$',
    priceAmount: 400,
    durationMinutes: 120,
    openingHours: '13:00 - 23:00',
    imageUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=1200&q=80',
    tags: ['Iconic Theatre', 'Irish Coffee', 'Bohemian', 'Culture', 'Art'],
    isFeatured: true,
  },
  {
    id: 'mum-colaba-causeway',
    title: 'Colaba Causeway Flea & Antique Trail',
    description: 'Bustling commercial corridor packed with vintage compasses, silver bangles, street momos, and historic British-era bookstalls.',
    category: 'Attractions',
    city: 'Mumbai',
    latitude: 18.9217,
    longitude: 72.8315,
    address: 'Colaba Causeway, Colaba, Mumbai 400001',
    rating: 4.6,
    reviewCount: 13200,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '10:30 - 21:30',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Shopping', 'Flea Market', 'Street Food', 'Culture'],
    isFeatured: false,
  },
  {
    id: 'mum-film-city',
    title: 'Dadasaheb Phalke Chitranagari Bollywood Tour',
    description: 'Expansive 520-acre film city in Goregaon where major Bollywood blockbusters and daily TV shows are produced with authentic studio backlots.',
    category: 'Attractions',
    city: 'Mumbai',
    latitude: 19.1557,
    longitude: 72.8833,
    address: 'Film City Rd, Goregaon East, Mumbai 400065',
    rating: 4.4,
    reviewCount: 3900,
    priceTier: '$$$',
    priceAmount: 750,
    durationMinutes: 180,
    openingHours: '10:00 - 17:00',
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=80',
    tags: ['Bollywood', 'Film Sets', 'Studio Tour', 'Culture', 'History'],
    isFeatured: false,
  },
  {
    id: 'mum-sassoon-docks',
    title: 'Sassoon Docks Morning Heritage & Murals',
    description: 'One of Mumbai\'s oldest open-sea docks built in 1875, buzzing with Koli fishermen and transformed with striking street art murals by St+art India.',
    category: 'Attractions',
    city: 'Mumbai',
    latitude: 18.9142,
    longitude: 72.8242,
    address: 'Sassoon Dock, Colaba, Mumbai 400005',
    rating: 4.5,
    reviewCount: 2800,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 60,
    openingHours: '05:00 - 12:00',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80',
    tags: ['Street Art', 'Fishing Harbor', 'Photography', 'Heritage', 'Culture'],
    isFeatured: false,
  },
  {
    id: 'mum-manis',
    title: 'Mani\'s Lunch Home Authentic Filter Coffee',
    description: 'Beloved Matunga South Indian institution serving fluffy steaming idlis, crispy medu vadas, and golden filter coffee served in brass davarahs.',
    category: 'Food',
    city: 'Mumbai',
    latitude: 19.0270,
    longitude: 72.8565,
    address: 'Komala Vilas, Matunga East, Mumbai 400019',
    rating: 4.7,
    reviewCount: 5100,
    priceTier: '$',
    priceAmount: 90,
    durationMinutes: 45,
    openingHours: '07:00 - 21:00',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80',
    tags: ['South Indian', 'Idli Vada', 'Matunga', 'Traditional', 'Food'],
    isFeatured: false,
  },
  {
    id: 'mum-pali-hill',
    title: 'Pali Hill Artisan Cafes & Street Art Walk',
    description: 'Leafy, tranquil Bandra neighborhood famed for boutique roasteries, charming bungalows, craft bakeries, and vibrant graffiti alleys.',
    category: 'Nightlife',
    city: 'Mumbai',
    latitude: 19.0620,
    longitude: 72.8290,
    address: 'Pali Hill, Bandra West, Mumbai 400050',
    rating: 4.7,
    reviewCount: 4600,
    priceTier: '$$$',
    priceAmount: 950,
    durationMinutes: 120,
    openingHours: '10:00 - 01:00',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    tags: ['Boutique Cafes', 'Cocktails', 'Bandra', 'Trendy', 'Nightlife'],
    isFeatured: false,
  },

  // London
  {
    id: 'lon-st-pauls',
    title: 'St Paul\'s Cathedral & Whispering Gallery',
    description: 'Sir Christopher Wren\'s iconic 17th-century masterpiece with a world-famous dome, whispering gallery acoustic marvel, and golden cross skyline views.',
    category: 'Attractions',
    city: 'London',
    latitude: 51.5138,
    longitude: -0.0984,
    address: 'St. Paul\'s Churchyard, London EC4M 8AD',
    rating: 4.8,
    reviewCount: 19200,
    priceTier: '$$$',
    priceAmount: 25,
    durationMinutes: 120,
    openingHours: '08:30 - 16:30 (Wed from 10:00)',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
    tags: ['Wren Architecture', 'Dome Views', 'History', 'Culture'],
    isFeatured: true,
  },
  {
    id: 'lon-columbia-flower',
    title: 'Columbia Road Sunday Flower Market',
    description: 'East London\'s most vibrant Sunday morning ritual where historic Victorian terraced shops transform into an ocean of cut flowers, plants, and vintage pottery.',
    category: 'Attractions',
    city: 'London',
    latitude: 51.5289,
    longitude: -0.0713,
    address: 'Columbia Rd, London E2 7RG',
    rating: 4.7,
    reviewCount: 7800,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '08:00 - 15:00 (Sundays only)',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    tags: ['Flowers', 'Artisan Bakery', 'East London', 'Nature', 'Sunday Vibe'],
    isFeatured: false,
  },
  {
    id: 'lon-globe',
    title: 'Shakespeare\'s Globe Open-Air Yard Experience',
    description: 'Faithful oak-and-thatch reconstruction of William Shakespeare\'s 1599 Elizabethan playhouse on the South Bank, offering standing yard tickets for £5-£10.',
    category: 'Events',
    city: 'London',
    latitude: 51.5081,
    longitude: -0.0972,
    address: '21 New Globe Walk, London SE1 9DT',
    rating: 4.8,
    reviewCount: 11500,
    priceTier: '$',
    priceAmount: 10,
    durationMinutes: 150,
    openingHours: '10:00 - 18:00 (Evening performances till 22:30)',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
    tags: ['Elizabethan Theatre', 'Shakespeare', 'History', 'Art', 'Culture'],
    isFeatured: false,
  },
  {
    id: 'lon-kew',
    title: 'Kew Royal Botanic Gardens & Temperate House',
    description: 'UNESCO World Heritage botanical wonderland housing the world\'s largest living plant collection, soaring Victorian glasshouses, and treetop canopy walk.',
    category: 'Parks',
    city: 'London',
    latitude: 51.4787,
    longitude: -0.2956,
    address: 'Kew, Richmond, London TW9 3AE',
    rating: 4.9,
    reviewCount: 22000,
    priceTier: '$$',
    priceAmount: 20,
    durationMinutes: 210,
    openingHours: '10:00 - 19:00',
    imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1200&q=80',
    tags: ['UNESCO Botanical', 'Glasshouses', 'Treetop Walkway', 'Nature', 'Peaceful'],
    isFeatured: true,
  },
  {
    id: 'lon-brick-lane',
    title: 'Brick Lane Street Art & Beigel Bake',
    description: 'Legendary 24/7 East End Jewish bakery serving warm salt beef and hot mustard beigels amidst cutting-edge Banksy and Roa street art.',
    category: 'Food',
    city: 'London',
    latitude: 51.5245,
    longitude: -0.0719,
    address: '159 Brick Lane, London E1 6SB',
    rating: 4.7,
    reviewCount: 14800,
    priceTier: '$',
    priceAmount: 8,
    durationMinutes: 60,
    openingHours: 'Open 24 hours',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Salt Beef Beigel', 'Graffiti Tour', 'Food', 'History', 'Culture'],
    isFeatured: false,
  },
  // ==========================================
  // AHMEDABAD EXPERIENCES
  // ==========================================
  {
    id: 'amd-sabarmati-ashram',
    title: 'Sabarmati Ashram (Gandhi Ashram)',
    description: 'Mahatma Gandhi’s tranquil riverside headquarters from 1917 to 1930. Explore Hriday Kunj, spinning wheel artifacts, and the serene museum gallery.',
    category: 'Attractions',
    city: 'Ahmedabad',
    latitude: 23.0605,
    longitude: 72.5802,
    address: 'Gandhi Smarak Sangrahalaya, Ashram Road, Ahmedabad 380027',
    rating: 4.8,
    reviewCount: 9200,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '08:30 - 18:30',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    tags: ['Historic', 'Gandhi Heritage', 'Peaceful', 'Museum', 'Riverfront'],
    isFeatured: true,
  },
  {
    id: 'amd-adalaj-stepwell',
    title: 'Adalaj Stepwell (Rudabai Stepwell)',
    description: 'A breathtaking 15th-century five-story underground stepwell blending Hindu and Islamic Solanki craftsmanship with intricately carved sandstone pillars.',
    category: 'Attractions',
    city: 'Ahmedabad',
    latitude: 23.1667,
    longitude: 72.5801,
    address: 'Adalaj, Gandhinagar Highway, Ahmedabad 382421',
    rating: 4.7,
    reviewCount: 7800,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 75,
    openingHours: '08:00 - 18:00',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    tags: ['Architecture', 'Stepwell', 'Heritage', 'Ancient Art', 'Photography'],
    isFeatured: true,
  },
  {
    id: 'amd-sidi-saiyyed',
    title: 'Sidi Saiyyed Mosque',
    description: 'World-famous 1573 mosque celebrated for its delicately carved marble-latticework screens depicting the iconic intertwining "Tree of Life".',
    category: 'Attractions',
    city: 'Ahmedabad',
    latitude: 23.0264,
    longitude: 72.5815,
    address: 'Bhadra, Opposite Electricity House, Ahmedabad 380001',
    rating: 4.7,
    reviewCount: 5400,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 45,
    openingHours: '07:00 - 19:00',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    tags: ['Tree of Life', 'Historic', 'Architecture', 'Stone Carving', 'Culture'],
    isFeatured: false,
  },
  {
    id: 'amd-manek-chowk',
    title: 'Manek Chowk Street Food Market',
    description: 'Ahmedabad’s legendary late-night food carnival in the historic walled city, famed for Gwalior butter dosas, chocolate cheese sandwiches, and kulfi.',
    category: 'Food',
    city: 'Ahmedabad',
    latitude: 23.0238,
    longitude: 72.5898,
    address: 'Old City, Khadia, Ahmedabad 380001',
    rating: 4.6,
    reviewCount: 11200,
    priceTier: '$',
    priceAmount: 200,
    durationMinutes: 90,
    openingHours: '20:00 - 02:00',
    imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=1200&q=80',
    tags: ['Street Food', 'Nightlife', 'Late Night', 'Iconic', 'Desserts'],
    isFeatured: true,
  },
  {
    id: 'amd-house-of-mg',
    title: 'Agashiye at The House of MG',
    description: 'Acclaimed terrace fine dining restaurant situated in a grand 1924 heritage mansion, serving an opulent multi-course traditional Gujarati thali.',
    category: 'Food',
    city: 'Ahmedabad',
    latitude: 23.0279,
    longitude: 72.5816,
    address: 'Opposite Sidi Saiyyed Mosque, Lal Darwaja, Ahmedabad 380001',
    rating: 4.8,
    reviewCount: 6100,
    priceTier: '$$$',
    priceAmount: 1100,
    durationMinutes: 120,
    openingHours: '12:00 - 15:30, 19:00 - 23:00',
    imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=1200&q=80',
    tags: ['Gujarati Thali', 'Heritage Mansion', 'Fine Dining', 'Rooftop', 'Culture'],
    isFeatured: true,
  },
  {
    id: 'amd-riverfront-sports',
    title: 'Sabarmati Riverfront Promenade & Boating',
    description: 'State-of-the-art waterfront promenade with cycling trails, speedboating, riverfront flower park, and sunset boat rides across the Sabarmati river.',
    category: 'Adventure',
    city: 'Ahmedabad',
    latitude: 23.0315,
    longitude: 72.5718,
    address: 'Sabarmati Riverfront, West Bank, Ahmedabad 380009',
    rating: 4.6,
    reviewCount: 8400,
    priceTier: '$',
    priceAmount: 150,
    durationMinutes: 90,
    openingHours: '09:00 - 21:00',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Boating', 'Riverfront Walk', 'Adventure', 'Sunset Views', 'Cycling'],
    isFeatured: true,
  },
  {
    id: 'amd-science-city',
    title: 'Gujarat Science City',
    description: 'Expansive tech complex featuring India’s premier Aquatic Gallery with 68 tanks, dynamic Robotics Gallery with dancing robots, and an IMAX 3D Theatre.',
    category: 'Museums',
    city: 'Ahmedabad',
    latitude: 23.0807,
    longitude: 72.4965,
    address: 'Science City Road, Sola, Ahmedabad 380060',
    rating: 4.7,
    reviewCount: 9700,
    priceTier: '$$',
    priceAmount: 350,
    durationMinutes: 180,
    openingHours: '10:00 - 19:30',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    tags: ['Robotics', 'Aquarium', 'IMAX 3D', 'Science', 'Family Friendly'],
    isFeatured: false,
  },
  {
    id: 'amd-kankaria-lake',
    title: 'Kankaria Lake & Balloon Safari',
    description: 'Historic 15th-century polygonal lake offering hot-air balloon tethered flights, Nagina Wadi musical fountains, zoo, and mini toy train joyrides.',
    category: 'Parks',
    city: 'Ahmedabad',
    latitude: 23.0063,
    longitude: 72.6027,
    address: 'Maninagar, Ahmedabad 380022',
    rating: 4.5,
    reviewCount: 13500,
    priceTier: '$',
    priceAmount: 80,
    durationMinutes: 120,
    openingHours: '09:00 - 22:00',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    tags: ['Lake Walk', 'Toy Train', 'Balloon Safari', 'Fountains', 'Parks'],
    isFeatured: false,
  },
  {
    id: 'amd-sarkhej-roza',
    title: 'Sarkhej Roza',
    description: 'Poetic Sufi architectural ensemble acclaimed by Le Corbusier as the "Acropolis of Ahmedabad", overlooking a massive excavated lake basin.',
    category: 'Attractions',
    city: 'Ahmedabad',
    latitude: 22.9785,
    longitude: 72.5028,
    address: 'Post Jeevraj Park, Sarkhej Makarba Road, Ahmedabad 380051',
    rating: 4.7,
    reviewCount: 4200,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '08:00 - 18:00',
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
    tags: ['Sufi Heritage', 'Islamic Architecture', 'Peaceful', 'Historic', 'Photography'],
    isFeatured: false,
  },
  {
    id: 'amd-law-garden',
    title: 'Law Garden Khau Galli & Handicrafts',
    description: 'Lively evening bazaar packed with colorful Gujarati traditional Kutchi embroidered textiles, bandhani sarees, and hot street snacks.',
    category: 'Food',
    city: 'Ahmedabad',
    latitude: 23.0248,
    longitude: 72.5583,
    address: 'Netaji Road, Ellisbridge, Ahmedabad 380006',
    rating: 4.5,
    reviewCount: 7100,
    priceTier: '$',
    priceAmount: 150,
    durationMinutes: 90,
    openingHours: '18:00 - 23:30',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Handicrafts', 'Textiles', 'Khau Galli', 'Street Food', 'Shopping'],
    isFeatured: false,
  },
  {
    id: 'amd-amdavad-ni-gufa',
    title: 'Amdavad ni Gufa & CEPT Art Gallery',
    description: 'Underground cave-like art gallery designed by Pritzker laureate B.V. Doshi with vivid murals painted directly on curved mosaic walls by M.F. Husain.',
    category: 'Museums',
    city: 'Ahmedabad',
    latitude: 23.0378,
    longitude: 72.5503,
    address: 'Kasturbhai Lalbhai Campus, University Road, Ahmedabad 380009',
    rating: 4.6,
    reviewCount: 3800,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 60,
    openingHours: '16:00 - 20:00',
    imageUrl: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80',
    tags: ['Modern Art', 'Architecture', 'Cave Gallery', 'Husain Murals', 'Culture'],
    isFeatured: false,
  },
  {
    id: 'amd-das-khaman',
    title: 'Das Khaman Heritage Snack Shop',
    description: 'Legendary Gujarati snack institution founded in 1922. Famous for steaming hot, melt-in-mouth nylon khaman, sev khamani, and fried green chillies.',
    category: 'Food',
    city: 'Ahmedabad',
    latitude: 23.0182,
    longitude: 72.5765,
    address: 'Shop No 2, Trade Centre, Stadium Cross Road, Navrangpura, Ahmedabad 380009',
    rating: 4.7,
    reviewCount: 4600,
    priceTier: '$',
    priceAmount: 90,
    durationMinutes: 45,
    openingHours: '07:30 - 21:00',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80',
    tags: ['Khaman', 'Gujarati Snacks', 'Breakfast', 'Iconic', 'Local Favorite'],
    isFeatured: false,
  },
  {
    id: 'amd-hutheesing-temple',
    title: 'Hutheesing Jain Temple',
    description: 'Elegantly carved 1848 white marble Jain temple with a courtyard of 52 sub-shrines and an intricate Mahavira marble tower of victory.',
    category: 'Attractions',
    city: 'Ahmedabad',
    latitude: 23.0422,
    longitude: 72.5936,
    address: 'Shahibaug Road, Bardolpura, Ahmedabad 380004',
    rating: 4.7,
    reviewCount: 3900,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 60,
    openingHours: '08:00 - 17:00',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    tags: ['Jain Temple', 'Marble Carving', 'Historic', 'Peaceful', 'Architecture'],
    isFeatured: false,
  },
  {
    id: 'amd-calico-museum',
    title: 'Calico Museum of Textiles',
    description: 'World-renowned museum housing an extraordinary historic collection of Indian fabrics, court costumes, Kashmiri shawls, and religious tapestries.',
    category: 'Museums',
    city: 'Ahmedabad',
    latitude: 23.0567,
    longitude: 72.5982,
    address: 'The Retreat, Shahibaug, Ahmedabad 380004',
    rating: 4.8,
    reviewCount: 2900,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 120,
    openingHours: '10:15 - 12:30 (Closed Wed)',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80',
    tags: ['World Famous', 'Textile Heritage', 'Museum', 'Historic Fabrics', 'Culture'],
    isFeatured: false,
  },
];
