import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SEED_CATEGORIES = [
  { id: 'cat-attractions', name: 'Attractions', slug: 'attractions', icon: 'Compass', sortOrder: 1 },
  { id: 'cat-museums', name: 'Museums', slug: 'museums', icon: 'Landmark', sortOrder: 2 },
  { id: 'cat-food', name: 'Food', slug: 'food', icon: 'UtensilsCrossed', sortOrder: 3 },
  { id: 'cat-parks', name: 'Parks', slug: 'parks', icon: 'Trees', sortOrder: 4 },
  { id: 'cat-nightlife', name: 'Nightlife', slug: 'nightlife', icon: 'Moon', sortOrder: 5 },
  { id: 'cat-adventure', name: 'Adventure', slug: 'adventure', icon: 'Mountain', sortOrder: 6 },
  { id: 'cat-events', name: 'Events', slug: 'events', icon: 'Calendar', sortOrder: 7 },
];

const SEED_EXPERIENCES = [
  // BENGALURU
  {
    id: 'blr-palace',
    title: 'Bangalore Palace',
    description: 'Tudor-style royal estate with wooden carvings, grand chandeliers, and manicured gardens built by Chamaraja Wodeyar in 1878.',
    category: 'Attractions',
    city: 'Bengaluru',
    latitude: 12.9988,
    longitude: 77.5921,
    address: 'Vasanth Nagar, Bengaluru, Karnataka 560052',
    rating: 4.6,
    reviewCount: 4820,
    priceTier: '$$',
    priceAmount: 250,
    durationMinutes: 120,
    openingHours: '10:00 - 17:30',
    imageUrl: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    tags: ['Historic', 'Royal Heritage', 'Architecture'],
    isFeatured: true,
  },
  {
    id: 'blr-visvesvaraya',
    title: 'Visvesvaraya Industrial & Technological Museum',
    description: 'Interactive science wonderland with four floors of hands-on exhibits, aerospace engine models, and 3D dinosaur shows.',
    category: 'Museums',
    city: 'Bengaluru',
    latitude: 12.9752,
    longitude: 77.5963,
    address: 'Kasturba Road, Sampangi Rama Nagar, Bengaluru 560001',
    rating: 4.7,
    reviewCount: 3640,
    priceTier: '$',
    priceAmount: 85,
    durationMinutes: 120,
    openingHours: '09:30 - 18:00',
    imageUrl: 'https://images.unsplash.com/photo-1569437061241-a848be43cc82?auto=format&fit=crop&w=1200&q=80',
    tags: ['Science', 'Family Friendly', 'Interactive'],
    isFeatured: true,
  },
  {
    id: 'blr-cubbon-park',
    title: 'Cubbon Park',
    description: 'A 300-acre lush green haven nestled in the heart of Bengaluru, shaded by bamboo groves and colonial memorials.',
    category: 'Parks',
    city: 'Bengaluru',
    latitude: 12.9763,
    longitude: 77.5929,
    address: 'Kasturba Road, Bengaluru, Karnataka 560001',
    rating: 4.8,
    reviewCount: 9150,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: '06:00 - 19:00',
    imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Nature', 'Walking', 'Peaceful'],
    isFeatured: true,
  },
  {
    id: 'blr-toit',
    title: 'Toit Brewpub Indiranagar',
    description: 'Iconic microbrewery celebrated for craft ales, Belgian beer, wood-fired pizza, and vibrant weekend social vibe.',
    category: 'Nightlife',
    city: 'Bengaluru',
    latitude: 12.9792,
    longitude: 77.6408,
    address: '100ft Road, Indiranagar, Bengaluru 560038',
    rating: 4.8,
    reviewCount: 11200,
    priceTier: '$$$',
    priceAmount: 1200,
    durationMinutes: 150,
    openingHours: '12:00 - 00:30',
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
    tags: ['Craft Beer', 'Dining', 'Social Hub'],
    isFeatured: false,
  },
  {
    id: 'blr-vidyarthi-bhavan',
    title: 'Vidyarthi Bhavan Masala Dosa',
    description: 'Legendary Gandhi Bazaar heritage restaurant serving crispy ghee-laden masala dosas and filter coffee since 1943.',
    category: 'Food',
    city: 'Bengaluru',
    latitude: 12.9431,
    longitude: 77.5714,
    address: 'Gandhi Bazaar Main Rd, Basavanagudi, Bengaluru 560004',
    rating: 4.7,
    reviewCount: 8400,
    priceTier: '$',
    priceAmount: 120,
    durationMinutes: 60,
    openingHours: '06:30 - 11:30, 14:00 - 20:00',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80',
    tags: ['South Indian', 'Breakfast', 'Heritage'],
    isFeatured: true,
  },
  // MUMBAI
  {
    id: 'mum-gateway',
    title: 'Gateway of India',
    description: 'Grand Indo-Saracenic basalt arch built overlooking the Arabian Sea, standing as the quintessential monument of Mumbai.',
    category: 'Attractions',
    city: 'Mumbai',
    latitude: 18.9220,
    longitude: 72.8347,
    address: 'Apollo Bandar, Colaba, Mumbai, Maharashtra 400001',
    rating: 4.7,
    reviewCount: 16500,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 60,
    openingHours: 'Open 24 hours',
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Iconic Landmark', 'Arabian Sea', 'Photography'],
    isFeatured: true,
  },
  {
    id: 'mum-marine-drive',
    title: 'Marine Drive "Queen\'s Necklace" Promenade',
    description: 'A breezy 3.6-kilometer seaside boulevard hugging Back Bay, famous for sunset watchers and Art Deco buildings.',
    category: 'Parks',
    city: 'Mumbai',
    latitude: 18.9432,
    longitude: 72.8230,
    address: 'Netaji Subhash Chandra Bose Road, Mumbai 400020',
    rating: 4.9,
    reviewCount: 21000,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 90,
    openingHours: 'Open 24 hours',
    imageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80',
    tags: ['Sunset', 'Sea Breeze', 'Art Deco'],
    isFeatured: true,
  },
  {
    id: 'mum-chowpatty-food',
    title: 'Street Food Crawl at Girgaon Chowpatty',
    description: 'Savor spicy pav bhaji slathered with Amul butter, tangy bhel puri, and saffron rabdi kulfi directly facing the twilight sea.',
    category: 'Food',
    city: 'Mumbai',
    latitude: 18.9548,
    longitude: 72.8142,
    address: 'Girgaon Chowpatty, Marine Drive, Mumbai 400007',
    rating: 4.7,
    reviewCount: 7100,
    priceTier: '$',
    priceAmount: 180,
    durationMinutes: 75,
    openingHours: '16:00 - 23:30',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80',
    tags: ['Street Food', 'Pav Bhaji', 'Chaat'],
    isFeatured: true,
  },
  // LONDON
  {
    id: 'lon-tower',
    title: 'Tower of London & Crown Jewels',
    description: 'Nearly 1,000 years of royal intrigue, medieval fortresses, White Tower armory, and dazzling priceless Crown Jewels.',
    category: 'Attractions',
    city: 'London',
    latitude: 51.5081,
    longitude: -0.0759,
    address: 'London EC3N 4AB, United Kingdom',
    rating: 4.8,
    reviewCount: 18200,
    priceTier: '$$$',
    priceAmount: 34,
    durationMinutes: 180,
    openingHours: '09:00 - 17:30',
    imageUrl: 'https://images.unsplash.com/photo-1520986606214-8b456906c813?auto=format&fit=crop&w=1200&q=80',
    tags: ['Royal History', 'Crown Jewels', 'Medieval Fortress'],
    isFeatured: true,
  },
  {
    id: 'lon-british-museum',
    title: 'The British Museum & Great Court',
    description: 'World-renowned treasury of 8 million works exploring human history and culture, including the Rosetta Stone.',
    category: 'Museums',
    city: 'London',
    latitude: 51.5194,
    longitude: -0.1270,
    address: 'Great Russell St, Bloomsbury, London WC1B 3DG',
    rating: 4.9,
    reviewCount: 24500,
    priceTier: 'Free',
    priceAmount: 0,
    durationMinutes: 180,
    openingHours: '10:00 - 17:00',
    imageUrl: 'https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?auto=format&fit=crop&w=1200&q=80',
    tags: ['Ancient Civilizations', 'Rosetta Stone', 'Must Visit'],
    isFeatured: true,
  },
  {
    id: 'lon-borough-market',
    title: 'Borough Market Artisanal Food Tour',
    description: 'Historic market under Victorian railway arches packed with artisan cheesemongers, sizzling chorizo rolls, and fresh oysters.',
    category: 'Food',
    city: 'London',
    latitude: 51.5055,
    longitude: -0.0906,
    address: '8 Southwark St, London SE1 1TL',
    rating: 4.8,
    reviewCount: 16900,
    priceTier: '$$',
    priceAmount: 22,
    durationMinutes: 90,
    openingHours: '10:00 - 17:00',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Gourmet Street Food', 'Cheese & Wine', 'Historic Market'],
    isFeatured: true,
  },
];

async function main() {
  console.log('Seeding categories...');
  for (const cat of SEED_CATEGORIES) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    });
  }

  console.log('Seeding experiences...');
  for (const exp of SEED_EXPERIENCES) {
    await prisma.experience.upsert({
      where: { id: exp.id },
      update: exp,
      create: exp,
    });
  }

  console.log('Database seeded successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
